# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f0ad015a728463f971515a901933d6a2153851628f1c072e767c78612193e255ae2065dd9e3ee9af6048e1b30b6c04e50f544b1f5432900bb5b737136ee4178

test:
  secret_key_base: 7af1a046af97f6cdcbe29653f861f1a255bcf2e40e66487cd30e6f869eb32439f7772e5baf77ed61bd358d2b6102c70f554769e60bbb19abbb06a8d9a4c74998

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
